### ISSUE TITLE
measurementTypeID 

### ISSUE THREAD

**Issue by melinalou** [iobis/env-data#27]
Hi!I have a dataset from a provider that contains measurements about length and weight. Trying to find the related measurementTypeID I think that this could be ok for the length http://vocab.nerc.ac.uk/collection/P01/current/TL01XX01/ but I can not find something about weight. Can you help me?
Thanks!

**Comment by rubenpp7** [comment]
Hi, 

for length you have a few options:
https://vocab.nerc.ac.uk/search_nvs/P01/?searchstr=length%25biological%25entity&options=identifier,preflabel,altlabel,status_accepted&rbaddfilter=inc&searchstr2=

Weight measurements can be found in this search:
https://vocab.nerc.ac.uk/search_nvs/P01/?searchstr=weight%25biological%25entity&options=identifier,preflabel,altlabel,status_accepted&rbaddfilter=inc&searchstr2=

Probably http://vocab.nerc.ac.uk/collection/P01/current/SPWGXX01 will be adequate if you don't have units and the organisms are not processed

**Comment by melinalou** [comment]
Thank you!

**Comment by rubenpp7** [comment]
Happy to help @melinalou
please remember to close the issue if solved :)
