### ISSUE TITLE
Bio check, ipt test mode

### ISSUE THREAD

**Issue by melinalou** [iobis/env-data#28]
Hi!We are trying to test our dataset with [Bio](https://rshiny.lifewatch.be/BioCheck/) using the url from the test mode of ipt.The BioCheck is not working, firstly has an error about invalid character $ and then it doesn't load at all. Is there something we could do?

**Comment by rubenpp7** [comment]
Could you share the IPT resource or DwC-Archive that is failing? Also, please transfer the issue to https://github.com/EMODnet/EMODnetBiocheck/issues

**Comment by rubenpp7** [comment]
Hi @melinalou 

is this issue the same as https://github.com/EMODnet/EMODnetBiocheck/issues/48 
if so, are they fixed? If so, please close the issues
