### ISSUE TITLE
NERC Vocabulary Server

### ISSUE THREAD

**Issue by melinalou** [iobis/env-data#29]
Hi!
Could you please let us know what is the procedure to follow in order to add into the NERC Vocabulary Server , a new sampling device? The description of this device is available by our HCMR colleagues. 
Maybe there is a related section for this issue but I could not find it.
Thanks in advance!

**Comment by rubenpp7** [comment]
Hi @melinalou 

The following link should help :)
https://github.com/nvs-vocabs/L22?tab=readme-ov-file#path-to-requesting-a-new-term
