### ISSUE TITLE
occurrence as core table

### ISSUE THREAD

**Issue by melinalou** [iobis/env-data#30]
Hi!
When we have as a core the occurrence table without event table how can we pass the detection depth of the observation (minimumDepthInMeters and maximumDepthInMeters)?
Thanks in advance!

**Comment by pieterprovoost** [comment]
@melinalou `minimumDepthInMeters` and `maximumDepthInMeters` are part of the occurrence core as well, see https://rs.gbif.org/core/dwc_occurrence_2024-02-23.xml

**Comment by melinalou** [comment]
Thanks a lot!
