### ISSUE TITLE
Ipt test mode problems

### ISSUE THREAD

**Issue by melinalou** [iobis/env-data#31]
Hi!
I am trying to access the https://ipt.vliz.be/upload/manage and it is not working, with the following warnings:

![image](https://github.com/iobis/env-data/assets/117156896/8a0d3743-5099-4763-87b6-c421397486b2)

Can you help me with this?

Thank you!
All the best,
Melina

**Comment by rubenpp7** [comment]
Hi @melinalou 

Could you confirm that you are logged in?
Also that you are trying to access the overview of datasets under the "Manage resources" tab?

Or is this happening with a specific IPT resource?

**Comment by melinalou** [comment]
Hi @rubenpp7
Yes I was logged in. The warnings appeared in the main ipt page.
It is fixed now!
Thank you!

**Comment by rubenpp7** [comment]
Awesome!! :)
Could you close the issue please?
